
version: '3'
services:
  db:
    image: postgres:9.6-alpine
    volumes:
      - ./docker/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
